appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Tm3WmiCVnyxNX2WQNs2Gwt8TdVnygDaa0Xk0KZxc14pjiMLD8SWHwY+WovK0SvU0mbI0IFU8y1axMpJjjXMhYlbDWcr3oP0xJOQlDpJldmPh7ty2YwnShfHmS1sjA1afNOEpAghJ9aFMf916lQmQF8IZxsL5/Ne3gK8tj+bWtaxcspaFkOTP+1NWtxfCbVGy+ED0MrNJRXLxNpedmbHvsefjCuFiICJrzIQjAg66HChoziOsz26mUKwbQe40lu9WJuLDko6vYRf6OwJ1yxmi8Q4x9YwFRt9JVAZbjxN9Pq+g044GZnBi2lX4dLG5azcd8c1BtlKmW4sjIGG/XeP71oq24P6mUk+v95zZA2CBUq0g5CKfLpnhnYsc2i7EsP4LnfAiJNoy0cTGPresSuPo4OLCAY60bbIpyNyt7RGARvJCv/0w8HotJ1n2HQn6x9AM/YLwidtbaNQu/SlUY5oC/JH2evqa1fra44Xzc3PNCP8MJs2lURrRW1GF81eMV4ybOOTn5wcQh/rEhuVbHvqvW4+gGUJE9e6g5StKd3g4dqT8DthQfPoJtHL99AH+rG5jbhcKihSc+IeLEkLAYy0QLmLV8WILQ0NNecKnEAuOYGTICFNLNsVN61U8x4E8LvXIqptibjCalBu1vH0Dqco+ClBWVDBGPhfu7cPPBK5eUNI=
conda_forge_output_validation: true
